name: build-test-deploy
# Changed 'on' to enable this workflow to be called from other workflows
on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      python-version:
        description: "pthon version"
        required: true
        type: string

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      # Modified to use the python-version from the workflow inputs
      - name: use python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}



  test: 
    needs: build

    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      # Modified to use the python-version from the workflow inputs
      - name: use python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}
          
##     - name: execute python file
##run: python hello.py